# Generated by Django 5.0.1 on 2024-02-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
    ]
