# Generated by Django 5.0.1 on 2024-02-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_price_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=11000000),
            preserve_default=False,
        ),
    ]
