# Generated by Django 5.0.1 on 2024-02-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_sub_cat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='static/assets/img/transparent-photo-icon-for-your-interface-icon-picture-icon-5f9e5dcf942c94.2750417916042142236069copy.png', null=True, upload_to='products/'),
        ),
    ]
