# Generated by Django 5.0.1 on 2024-03-06 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_productcategory_is_sub_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='max_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.discountcode'),
        ),
    ]
